server:
  port: 8089

spring:
    datasource:
        url: jdbc:mysql://vm:3306/fitcare?useSSL=false&useUnicode=true&characterEncoding=utf-8
        username: developer
        password: ${MYSQL_DB_PASS}

    jpa:
        hibernate:
            ddl-auto: create-drop
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: mysql
        show-sql: true